spring.application.name=security

# R2DBC PostgreSQL
spring.r2dbc.url=r2dbc:postgresql://localhost:5432/erp
spring.r2dbc.username=postgres
spring.r2dbc.password=cuadrado27

# Inicialización SQL (opcional)
spring.sql.init.mode=always

# Puerto (opcional)
server.port=8081

jwt.secret=12345678901234567890123456789012
jwt.expiration=86400000

# Logs útiles para debug
logging.level.org.springframework.r2dbc=DEBUG
logging.level.org.springframework.security=DEBUG