spring.application.name=core

# R2DBC PostgreSQL
spring.r2dbc.url=r2dbc:postgresql://host.docker.internal:5432/erp
spring.r2dbc.username=postgres
spring.r2dbc.password=cuadrado27

# Inicializaci�n SQL (opcional)
spring.sql.init.mode=always

# Puerto (opcional)
server.port=8082

jwt.secret=12345678901234567890123456789012
jwt.expiration=86400000

# Logs �tiles para debug
logging.level.org.springframework.r2dbc=DEBUG
logging.level.org.springframework.security=DEBUG